# Practical 23

# Demonstrate Naive Bayes algorithm to predict wether the user will buy the product or not on User_Data. Compare the accuracy achieved with logistic regression and KNN

In [1]:
# import the libraries
import numpy as nm
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\Machine Learning\User_Data.csv")  #import the dataset

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
x = data.iloc[: , [2,3]].values  # independent fatures
y = data.iloc[: , 4].values

In [5]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split (x, y, test_size = 0.2, random_state = 4)

In [6]:
from sklearn.preprocessing import StandardScaler  #scaling 
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)  # Fit and transform training data
xtest = sc.transform(xtest)  # Transform test data.
xtest

array([[-0.47385841, -0.29866616],
       [-1.04895838,  0.3899427 ],
       [-1.24065838,  0.47601881],
       [ 0.00539156, -0.58558652],
       [-1.04895838,  0.50471084],
       [ 1.82654147, -1.27419538],
       [ 0.77219152,  0.50471084],
       [ 1.3472915 ,  1.93931264],
       [ 1.05974151,  0.53340288],
       [ 0.00539156, -0.55689448],
       [ 0.00539156, -0.3273582 ],
       [-1.04895838, -0.47081838],
       [-1.24065838,  0.27517456],
       [ 0.29294155, -0.29866616],
       [ 0.29294155, -0.55689448],
       [-0.37800842, -0.78643077],
       [-1.14480838, -0.52820245],
       [-1.14480838, -1.58980778],
       [-1.33650837, -0.44212634],
       [-1.33650837, -1.47503963],
       [-0.18630843, -0.47081838],
       [-0.95310839, -0.3273582 ],
       [-1.91160834,  0.33255863],
       [ 1.92239147,  0.7055551 ],
       [ 0.29294155,  0.04563827],
       [ 1.82654147,  1.48024007],
       [-1.04895838,  0.73424713],
       [ 0.19709155,  0.04563827],
       [-1.71990835,

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

GaussianNB()

In [8]:
ypred = classifier.predict(xtest) 
ypred

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest ,ypred)

In [10]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
print("Confusion Matrix: \n", confusion_matrix(ytest, ypred))  # Creating the confusion matrix.
print("Accuracy: \n", accuracy_score(ytest, ypred)*100)  # Finding the accuracy and report
print("Report: \n", classification_report(ytest, ypred))

Confusion Matrix: 
 [[54  5]
 [ 1 20]]
Accuracy: 
 92.5
Report: 
               precision    recall  f1-score   support

           0       0.98      0.92      0.95        59
           1       0.80      0.95      0.87        21

    accuracy                           0.93        80
   macro avg       0.89      0.93      0.91        80
weighted avg       0.93      0.93      0.93        80



In [11]:
print(" Gaussian Naive Bayes model  Accuracy is: ", accuracy_score(ytest, ypred)*100)  

 Gaussian Naive Bayes model  Accuracy is:  92.5


#### Conclusion